// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5f3SHUNVjNTaJlLGssa0_n6WAHXa7tW8',
    appId: '1:285146834725:web:20f345caa9c5acb2445ccc',
    messagingSenderId: '285146834725',
    projectId: 'whatsapp-clone-2003',
    authDomain: 'whatsapp-clone-2003.firebaseapp.com',
    storageBucket: 'whatsapp-clone-2003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYPK4vv4b8iz4hZV-bSFUxDgK_2u30uM8',
    appId: '1:285146834725:android:5fe57937f977af3c445ccc',
    messagingSenderId: '285146834725',
    projectId: 'whatsapp-clone-2003',
    storageBucket: 'whatsapp-clone-2003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfzv42ITuD2W8PMWfoZrdRtvuxx_9kx8',
    appId: '1:285146834725:ios:c200779889c0df97445ccc',
    messagingSenderId: '285146834725',
    projectId: 'whatsapp-clone-2003',
    storageBucket: 'whatsapp-clone-2003.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
